marian-small:
  batch_size: 8
  num_layers: 6
  num_heads: 8
marian-big:
  batch_size: 4
  num_layers: 6
  num_heads: 16
mbart50-1toM:
  batch_size: 1
  num_layers: 12
  num_heads: 16
  lang_map:
    eng: en_XX
    fra: fr_XX
    ita: it_IT
    nld: nl_XX
    ara: ar_AR
    tur: tr_TR
nllb:
  batch_size: 1
  num_layers: 12
  num_heads: 16
  lang_map:
    eng: eng_Latn
    fra: fra_Latn
    ita: ita_Latn
    nld: nld_Latn
    ara: ara_Arab
    tur: tur_Latn
gpt2:
  batch_size: 1
  num_layers: 12
  num_heads: 12
mistral:
  batch_size: 1
  num_layers: 32
  num_heads: 32
llama:
  batch_size: 1
  num_layers: 24
  num_heads: 16